[build]
  command = "npm run cms:build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  external_node_modules = ["sharp"]

[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--production=false"
  # CMS-specific environment variables
  CMS_CONTENT_PATH = "./content"
  CMS_MEDIA_PATH = "./public/uploads"
  NETLIFY_BUILD_HOOK = "true"

# Production build settings
[context.production]
  command = "npm run cms:build"
  environment = { NODE_ENV = "production" }

# Deploy preview settings for CMS content testing
[context.deploy-preview]
  command = "npm run cms:build"
  environment = { NODE_ENV = "preview" }

# Branch deploy settings
[context.branch-deploy]
  command = "npm run cms:build"

# Identity and Git Gateway settings for Decap CMS
[[plugins]]
  package = "netlify-plugin-git-gateway"

# Netlify Identity configuration
[context.production.environment]
  NETLIFY_IDENTITY_ENABLED = "true"
  NETLIFY_IDENTITY_SIGNUP = "invite_only"
  NETLIFY_IDENTITY_CONFIRM_IDENTITY = "true"
  NETLIFY_IDENTITY_RECOVERY = "true"
  NETLIFY_IDENTITY_EXTERNAL_PROVIDERS = "github"

# Identity widget configuration
[[headers]]
  for = "/.netlify/identity/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"

# Build optimization settings
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Cache settings for better build performance
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/uploads/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirect rules for CMS
[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301

# Build hooks for content updates
[build.ignore]
  command = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- content/ public/uploads/ || exit 1"
